pipeline {
  environment {
    registry = "shubhampadiya/gs-spring-boot-docker"
  }
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build Image') {
      steps{
	    script {
		    def mvnHome = tool 'apache-maven-3.2.1'
		    def dockerImage = sh "sudo ${mvnHome}/bin/mvn -f /var/lib/jenkins/workspace/Jenkins-docker/docker-java-maven/gs-spring-boot-docker-master/complete/pom.xml package dockerfile:build"
			}
		}
    }
    stage('Docker Image Push') {
      steps{
        script {
           docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
                    dockerImage.push()
          }
        }
      }
    }
  }
}
